<?php return array (
  'DEFAULT_MODULE' => 'Wap',
  'DB_HOST' => '127.0.0.1',
  'DB_NAME' => 'hongbao',
  'DB_USER' => 'root',
  'DB_PWD' => '#sy476476#ucq',
  'DB_PORT' => '3306',
  'DB_PREFIX' => 'haokuai_',
  'URL_MODEL' => 0,
  'TMPL_FILE_DEPR' => '_',
  'WX_TOKEN' => 'haokuai',
  'DB_TYPE' => 'mysql',
  'TMPL_ACTION_SUCCESS' => './Project//Common/View/success.html',
  'TMPL_ACTION_ERROR' => './Project//Common/View/error.html',
);